package com.openfx.constants;

public enum MySQLConstants {
	
	//system variables
	activate_all_roles_on_login("The server activates all roles granted to each account at login time","Y"),
	admin_address("The IP address on which to listen for TCP/IP connections on the administrative network interface","N"),
	admin_port("The TCP/IP port number to use for connections on the administrative network interface ","N"),
	admin_ssl_ca("It is like ssl_ca, except that it applies to the administrative connection interface rather than the main connection interface","Y"),
	admin_ssl_capath ("It applies to the administrative connection interface rather than the main connection interface","Y"),
	admin_ssl_cert("It is like ssl_cert, except that it applies to the administrative connection interface rather than the main connection interface.","Y"),
	admin_ssl_cipher ("It Is like ssl_cipher, except that it applies to the administrative connection interface rather than the main connection interface.","Y"),
	admin_ssl_crl("It s like ssl_crl, except that it applies to the administrative connection interface rather than the main connection interface.","Y"),
	admin_ssl_crlpath("It  is like ssl_crlpath, except that it applies to the administrative connection interface rather than the main connection interface.","Y"),
	admin_ssl_key("It  is like ssl_key, except that it applies to the administrative connection interface rather than the main connection interface","Y"),
	admin_tls_ciphersuites(" It applies to the administrative connection interface rather than the main connection interface.","Y"),
	admin_tls_version("Except that it applies to the administrative connection interface rather than the main connection interface","Y"),
	authentication_policy("It is used to administer multifactor authentication (MFA) capabilities","Y"),
	auto_generate_certs("This variable controls whether the server autogenerates SSL key and certificate files in the data directory, if they do not already exist.","N"),
	auto_increment_increment("AUTO_INCREEMENT columns are incremented by this value","Y"),
	autocommit("Sets the autocommit mode","Y"),
	automatic_sp_privileges("Creating and dropping stored procedures alters ACLs","Y"),
	avoid_temporal_upgrade("Whether ALTER TABLE should upgrade pre-5.6.4 temporal columns","Y"),
	back_log("Number of outstanding connection requests MySQL can have","N"),
	basedir("Path of installation directory","N"),
	big_tables("Allow big results sets by saving all temporary sets on file","Y"),
	bind_address("IP address or host name to bind to","N"),
	binlog_cache_size("Size of the cache to hold the SQL statements for the binary log during a transcation","Y"),
	binlog_checksum("Enable/disable binary log checksums","Y"),		
	binlog_direct_non_transactional_updates("Causes updates using statement format to nontransactional engines to be written directly to binary log.See documentation before using","Y"),

	binlog_encryption("",""),
	binlog_error_action("Controls what happens when the server cannot write to the binary log","Y"),
	binlog_expire_logs_auto_purge("","Y"),
	binlog_expire_logs_seconds("Purge binary logs after this many seconds","Y"),
	binlog_format("Specifies the format of the binary log","Y"),
	binlog_group_commit_sync_delay("Sets the number of microseconds to wait before synchronizing transactions to disk","Y"),
	binlog_group_commit_sync_no_delay_count("Sets the maximum number of transactions to wait for before aborting the current delay specified by bnlog_group_commit_sync_delay","Y"),
	binlog_gtid_simple_recovery("Controls how binary logs are iterated during GTID recovery","N"),
	binlog_max_flush_queue_time("How long to read transactions before flushing to binary log","Y"),
	binlog_order_commits("Whether to commit in same order aas writes to binary log","Y"),
	binlog_rotate_encryption_master_key_at_startup("","N"),
	binlog_row_event_max_size("","N"),
	binlog_row_image("Use full or minimal images when logging row changes","Y"),
	binlog_row_metadata("Configures the amount of table related metadata binary logged when using row-based logging","Y"),
	binlog_row_value_options("Enables binary logging of partial JSON updates for row-based replication","Y"),
	binlog_rows_query_log_events("When TRUE, enables logging of rows query log events in row-based logging mode.False by default.DO not enable when producing logs for pre-5.6 replication slaves or other readers.","Y"),
	binlog_stmt_cache_size("Size of the cache to hold nontransactional statements for the binary log during a transaction","Y"),
	binlog_transaction_compression("","Y"),
	binlog_transaction_compression_level_zstd("","Y"),
	binlog_transaction_dependency_history_size("Number of row hashes kept for looking up transaction that last updated some row","Y"),
	binlog_transaction_dependency_tracking("Source of dependency information(commit timestamps or transcation write sets)from which to assess which transactions can be executed in parallel by slave's multi-threaded applier","Y"),
	block_encryption_mode("Mode for block-based encryption algorithms","Y"),
	bulk_insert_buffer_size("Size of tree cache used in bulk insert optimization","Y"),
	caching_sha2_password_auto_generate_rsa_keys("Whether to autogenerate RSA key-pair files","N"),
	caching_sha2_password_digest_rounds("","N"),
	caching_sha2_password_private_key_path("SHA2 authentication plugin private key path name","N"),
	caching_sha2_password_public_key_path("SHA2 authentication plugin public key path name","N"),
	character_set_client("Current client character set","Y"),
	character_set_connection("Current connection character set","Y"),
	character_set_database("The character set used by the default databse","Y"),
	character_set_filesystem("Set the file system character set","Y"),
	character_set_results("Current result character set","Y"),
	character_set_server("Specify default character set","Y"),
	character_set_system("The character set used by the server for storing identifiers","N"),
	character_sets_dir("Directory where character sets are installed","N"),
	check_proxy_users("Whether built-in authentication plugins do proxying","Y"),
	collation_connection("The collation of connection","Y"),
	collation_database("The collation used by the default database","Y"),
	collation_server("Specify default collation","Y"),
	completion_type("Default completion type","Y"),
	concurrent_insert("USe concurrent insert with MyISAM","Y"),
	connect_timeout("Number of seconds the mysqlId server waits for a connect packet before responding with 'Bad handshake'","Y"),
	
	connection_memory_chunk_size("","Y"),
	connection_memory_limit("","Y"),
	core_file("Write core file on server crashes","N"),
	create_admin_listener_thread("","N"),
	cte_max_recursion_depth("Common table expression maximum recursion depth","Y"),
	datadir("Path of data directory","N"),
	default_authentication_plugin("The defualt authentication plugin","N"),
	default_collation_for_utf8mb4("Default collation for utf8mb4 character set","Y"),
	default_password_lifetime("Age in days when passwords effectively expire","Y"),
	default_storage_engine("The default storage engine(table type) for tables","Y"),
	default_table_encryption("","Y"),
	default_tmp_storage_engine("The default storage engine for TEMPORARY tables","Y"),
	default_week_format("The default mode value to use for the WEEK() function.","Y"),
	delay_key_write("The type of DELAY_KEY_WRITE ","Y"),
	delayed_insert_limit("After inserting delayed_insert_limit rows, the INSERT DELAYED handler will check if there are any SELECT statements pending.If so, it allows these to execute before continuing","Y"),
	delayed_insert_timeout("Hhow many seconds an INSERT DELAYED thread should wait for INSERT sttements before terminating","Y"),
	delayed_queue_size("What size queue(in rows) should be allocated for handling INSERT DELAYED","Y"),
	disabled_storage_engines("storage engines cannot be used to create tables","N"),
	disconnect_on_expired_password("Whether the server disconnects clients with expired passwords if clients cannot handle such accounts","N"),
	div_precision_increment("SCale of the result of '/' operator will be increased by this many digits","Y"),
	end_markers_in_json("Whether optimizer JSON output should add end markers.","Y"),
	enforce_gtid_consistency("Prevents execution of statements that cannot be logged in a transacionally safe manner","Y"),
	eq_range_index_dive_limit("The cutoff for switching from using index dives to index statistics","Y"),
	event_scheduler("Enable/Disable and start/stop the event scheduler.Note that this variable underwent significant changes in behaviour and permitted values in MySQL 5.1.11 and 5.1.12","Y"),
	expire_logs_days("Purge binary logs after this many days","Y"),
	explain_format("","Y"),
	explicit_defaults_for_timestamp(" Whether TIMESTAMP columns are nullable and have DEFAULT NULL","Y"),
	flush("Flush tables to disk between SQL statements","Y"),
	flush_time("A dedicated thread is created to flush all tables at the given interval","Y"),
	foreign_key_checks("If set to 1 (the default), foreign key constraints for InnoDB tables are checked","Y"),
	ft_boolean_syntax("List of operators for MATCH...AGAINST(... IN BOOLEAN MODE)","Y"),
	ft_max_word_len("The maximum length of the word to be included in a FULLTEXT index.Note:FULLTEXT indexes must be rebuilt after changing this variable.","N"),
	ft_min_word_len("The minimum length of the word to be included in a FULLTEXT index.Note:FULLTEXT indexes must be rebuilt after changing this variable.","N"),
	ft_query_expansion_limit("The number of best matches to use for QUERY EXPANSION.","N"),
	ft_stopword_file("Use stopwords from this file instead of built-in list","N"),
	general_log("Enable|Disable general log","Y"),
	general_log_file("The name of the general query log file. ","Y"),
	generated_random_password_length("","Y"),
	global_connection_memory_limit("","Y"),
	global_connection_memory_tracking("","Y"),
	group_concat_max_len("The maximum permitted result length in bytes for the GROUP_CONCAT() function. ","Y"),
	group_replication_consistency("","Y"),
	gtid_executed("Global:All GTIDs in the binary log(global) or current transaction(session).Read-only","N"),
	gtid_executed_compression_period("Compress gtid_executed table each time this many transactions have occurred.0 means never compress this table.Applies only when binary logging is disabled","Y"),
	gtid_mode("Controls whether GTID based logging is enabled and what type of transactions the logs can contain","Y"), 
	gtid_owned("The set of GTIDs owned by this client(session),or by all clients,together with the thread ID of the owner(global).Read-only.","N"),
	gtid_purged ("The set of all GTIDs that have been purged from the binary log","N"),
	have_compress("Availability of the xlib compression library","N"),
	have_dynamic_loading("Whether mysqld supports dynamic loading of plugins","N"),
	have_geometry("Whether mysqld supports spatial datatytpes","N"),
	have_openssl("Whether mysqld supports SSL connectiions","N"),
	have_profiling("Whether statement profiling capability is available","N"),
	have_query_cache("Whether mysqld supports query cache","N"),
	have_rtree_keys("YES if RTREE indexes are available, NO if not.(These are used for spatial indexes in MyISAM tables.)","N"),
	have_ssl("Whether mysqld supports SSL connections","N"),
	have_statement_timeout("Whether the statement execution timeout feature is available ","N"),
	have_symlink("YES if symbolic link support is enabled, NO if not.","N"),
	histogram_generation_max_mem_size("Maximum amount of memory available for generating histogram statistics","Y"),
	host_cache_size("Size of the host cache","Y"),
	hostname("The name of the server host","Y"),
	information_schema_stats_expiry(" session variable defines the period of time before cached statistics expire","Y"),
	init_connect("Statements that are executed for each new connection","Y"),
	init_file ("Read SQL statements from this file at startup","N"),
	init_replica ("","Y"),
	init_slave (" Statements that are executed when a slave connects to a master","Y"),
	innodb_adaptive_flushing("Control InnoDB adaptive flushing of dirty pages","Y"),
	innodb_adaptive_flushing_lwm("Low water mark representing percentage of redo log capacity at which adaptive flushing is enabled","Y"),
	innodb_adaptive_hash_index("Enable or Disable InnoDB adaptive hash indexes","Y"),
	innodb_adaptive_hash_index_parts("Partitions the adaptive hash index search system into n partitions,with each partition protected by a separate latch.Each index is bound to a specific partition based on space ID and index ID attributes","N"),
	innodb_adaptive_max_sleep_delay("Allows InnoDB to automatically adjust the value of innodb_thread_sleep_delay up or down according to the current workload","Y"),
	innodb_api_bk_commit_interval("Hoe often to auto-commit idle connections that use the InnoDB memcached interface,in seconds","Y"),
	innodb_api_disable_rowlock("","N"),
	innodb_api_enable_binlog("Lets you use the InnoDB memcached plugin with the MySQL binary log","N"),
	innodb_api_enable_mdl("Locks the table used by the InnoDB memcached plugin,so that it cannot be dropped or altered by DDL through the SQL interface","N"),
	innodb_api_trx_level("Lets you control the transaction isolation level on queries processed by the memcached interface","Y"),
	innodb_autoextend_increment("Data file autoextend increment in megabytes","Y"),
	innodb_autoinc_lock_mode("Set InnoDB auto-increment lock mode","N"),
	innodb_buffer_pool_chunk_size("Defines the chunk size that is used when resizing the buffer pool","N"),
	innodb_buffer_pool_dump_at_shutdown("Specifies whether to record the pages cached in the InnoDB buffer pool when the MySQL server is shutdown,to shorten the warmup process at the next restart","Y"),
	innodb_buffer_pool_dump_now("Immediately records the pages cached in the InnoDB buffer pool","Y"),
	innodb_buffer_pool_dump_pct("Specifies the percentage of the most recently used pages for each buffer pool to read out and dump","Y"),
	innodb_buffer_pool_filename("Specifies the file that holds the list of page numbers produced by innodb_buffer_pool_dump_at_shutdown or innodb_buffer_pool_dump_now","Y"),
	innodb_buffer_pool_in_core_file("","Y"),
	innodb_buffer_pool_instances("Specifies how many parts the InnoDB buffer pool is divided into","N"),
	innodb_buffer_pool_load_abort("Interrupts process of restoring InnoDB bufferpool contents triggered by innodb_buffer_pool_load_at_startup or innodb_buffer_pool_load_now ","Y"),
	innodb_buffer_pool_load_at_startup("Specifies that,on MySQL server setup, the InnoDB buffer pool is automatically \"warmed\" up by loading the same pages it held at an earlier time","N"),
	innodb_buffer_pool_load_now("Immediately \"warms up\" the InnoDB buffer pool by loading a set of data pages,without waiting for a server restart","Y"), 
	innodb_buffer_pool_size("Size of the memory buffer InnoDB uses to cache data and indexes of its tables","Y"),
	innodb_change_buffer_max_size("Maximum size for the InnoDB change buffer,as a percentage of the total size of buffer pool","Y"),
	innodb_change_buffering("Whether InnoDB performs insert buffering","Y"),
	innodb_checksum_algorithm("Specifies how to generate and verify the checksum stored in each disk block of each InnoDB tablespace","Y"),
	innodb_cmp_per_index_enabled("Enables per-index compression-related statistics in the INFORMATION_SCHEMA.INNODB_CMP_PER_INDEX table","Y"),
	innodb_commit_concurrency("Helps in performance tuning in heavily concurrent environments","Y"),
	innodb_compression_failure_threshold_pct("Sets the cuttoff point at which MySQL begins adding padding within compressed pages to avoid expensive compression failures","Y"),
	innodb_compression_level("Specifies the level of zlib compression to use for InnoDB compressed tables and indexes","Y"),
	innodb_compression_pad_pct_max("Specifies the maximum percentage that can be resserved as free space within each compressed page,to avoid compression failures when tightly packed data is recompressed","Y"),
	innodb_concurrency_tickets("Number of times a thread is allowed to enter InnoDB within the same SQL query it has once got the ticket","Y"),
	innodb_data_file_path("Path to individual files and their sizes","N"),
	innodb_data_home_dir ("The common part for InnoDB table spaces","N"),
	innodb_ddl_buffer_size("","Y"),
	innodb_ddl_threads("","Y"),
	innodb_deadlock_detect("Enables or disables deadlock detection","Y"),
	innodb_dedicated_server("Enables automatic configuration of buffer pool size,log file size, and flush method","N"),
	innodb_default_row_format("DEfines the default row format(ROW_FORMAT) for InnoDB tables","Y"),
	innodb_directories("Define directories to scan at startup for tabespace data files","N"),
	innodb_disable_sort_file_cache("Disable OS file system cache for merge-sort temporary files","Y"),
	innodb_doublewrite("Enable InnoDB doublewrite buffer","Y"),
	innodb_doublewrite_batch_size("","N"),
	innodb_doublewrite_dir("","N"),
	innodb_doublewrite_files("","N"),
	innodb_doublewrite_pages("","N"),
	innodb_extend_and_initialize("","Y"),
	innodb_fast_shutdown("Speeds up the shutdown process of the InnoDB storage engine","Y"),
	innodb_file_per_table("Stores each InnoDB table and its indexes in a separate .ibd file in the database directory","Y"),
	innodb_fill_factor("Defines the percentage B-tree leaf and non-leaf page space that is to be filled with data.The remaining space is reserved for future growth","Y"),
	innodb_flush_log_at_timeout("Write and flush logs every N seconds","Y"),
	innodb_flush_log_at_trx_commit("Set to 0(write and flush once per second),1(write and flush  at each commit) or 2(write at commit,flush once per second)","Y"),
	innodb_flush_method("Specifies to flush data","N"),
	innodb_flush_neighbors("Specifies whether or not flushing a page from the InnoDB buffer pool also flushes other dirty pages in the same extent","Y"),
	innodb_flush_sync("Enable innodb_flush_sync to ignore the innodb_io_capacity setting for bursts of I/O activity that occur at checkpoints.Disable innodb_flush_sync to adhere to the limit on I/O activity defined...","Y"),
	innodb_flushing_avg_loops("Number of iterartions for which InnoDB keeps the previously calculated snapshot of the flushing state,controlling how quickly adaptive flushing responds to changing workloads","Y"),
	innodb_force_load_corrupted("Lets InnoDB load tables at startup that are marked as corrupted;use only during troubleshootiing","N"),
	innodb_force_recovery("Helps to save your data in case the disk image of the database becomes corrupt","N"),
	innodb_fsync_threshold("","Y"),
	innodb_ft_aux_table ("Specifies which InnoDB table with a FULL TEXT index to examine by querying several innodb_ft_*tables in the information_schema","Y"),
	innodb_ft_cache_size("Size of the cache that holds a parsed document in memory while creating an InnoDB FULL TEXT index","N"),
	innodb_ft_enable_diag_print("Whether to enable additional full-text search diagnostic output","Y"),
	innodb_ft_enable_stopword("During creation of an InnoDB FULL TEXT index,omits stopwords from the search index","Y"),
	innodb_ft_max_token_size("Maximum length of words that are stored in an InnoDB FULL TEXT index","N"),
	innodb_ft_min_token_size("Minimum length of words that are stored in an InnoDB FULL TEXT index","N"),
	innodb_ft_num_word_optimize("Number of words to process during each OPTIMIZE TABLE operation on an InnoDB FULL TEXT index","Y"),
	innodb_ft_result_cache_limit("The InnoDB FULL TEXT search query result cache limit","Y"),
	innodb_ft_server_stopword_table("Specifies a table holdin a list of stopwords for InnoDB FULL TEXT indexes,which overrides the default stopword list and can be overridden by innodb_ft_user_stopword_table","Y"),
	innodb_ft_sort_pll_degree("Number of threads used to create an InnoDB FULL TEXT index in parallel,when building a search index for a large table","N"),
	innodb_ft_total_cache_size("The total memory allocated for the InnoDB FULL TEXT search index cache","N"),
	innodb_ft_user_stopword_table ("Speciifes a table holding a list of stopwords for InnoDB FULL TEXT indexes,which overrides the default stopword list and also innodb_ft_server_stopword_table","Y"),
	innodb_idle_flush_pct("","Y"),
	innodb_io_capacity("The limit on the maximum number of I/O operations per second","Y"),
	innodb_io_capacity_max("The limit up to which InnoDB is allowed to extend the inno_io_capacity setting in case of emergency","Y"),
	innodb_lock_wait_timeout("Timeout in seconds an InnoDB transaction may wait for a lock before a rollback occurs","Y"),
	innodb_log_buffer_size("Size of buffer which InnoDB uses to write log to the log files on disk","Y"),
	innodb_log_checksums("Enables or disables checksums for redo log pages","Y"),
	innodb_log_compressed_pages("Specifies whether images of re-compressed pages are stored in InnoDB redo logs","Y"),
	innodb_log_file_size("Size of each log file in a log group","N"),
	innodb_log_files_in_group("Number of InnoDB log files in the log group","N"),
	innodb_log_group_home_dir("Path to InnoDB log files","N"),
	innodb_log_spin_cpu_abs_lwm("Minimum amount of CPU usage below which user threads no longer spin while waiting for flushed redo","Y"),
	innodb_log_spin_cpu_pct_hwm("Maximum amount of CPU usage above which user threads no longer spin while waiting for flushed redo","Y"),
	innodb_log_wait_for_flush_spin_hwm("The maximum average log flush time beyond which user threads no longer spin while waiting for flushed redo","Y"),
	innodb_log_write_ahead_size("The write-ahead block size for the redo log","Y"),
	innodb_log_writer_threads("","Y"),
	innodb_lru_scan_depth("Influences the algorithms and heuristics for the flush operation for the InnoDB buffer pool","Y"),
	innodb_max_dirty_pages_pct("Percentage of dirty pages allowed in buffer pool","Y"),
	innodb_max_dirty_pages_pct_lwm("Low water mark representing percentage of dirty pages where preflushing is enabled to control the dirty page ratio","Y"),
	innodb_max_purge_lag("Desired maximum length of the purge queue(0=no limit)","Y"),
	innodb_max_purge_lag_delay("Specifies the maximum delay in milliseconds for the formula calculated using the innodb_max_purge_lag configuration option","Y"),
	innodb_max_undo_log_size("Sets the threshold for truncating the InnoDB undo log","Y"),
	innodb_monitor_disable ("Turns off one or more counters in the information_schema.innodb_metrics table","Y"),
	innodb_monitor_enable("Turns on one or more counters in the information_schema.innodb_metrics table","Y"),
	innodb_monitor_reset("Resets to zero the count value for one or more counters in the information_schema.innodb_metrics table","Y"),
	innodb_monitor_reset_all("Resets all values(minimum,maximum,and so on)for one or more counters in the information_schema.innodb_metrics table","Y"),
	innodb_old_blocks_pct("Percentage of the InnoDB buffer pool to reserve for old blocks","Y"),
	innodb_old_blocks_time("How long(in ms) blocks must remain in old end of InnoDB buffer pool before moving to new end","Y"),
	innodb_online_alter_log_max_size("Specifies an upper limit on size of the temporary log files used during online DDL operations for InnoDB tables","Y"),
	innodb_open_files("The maximum number of files that InnoDB keeps open at the same time","N"),
	innodb_optimize_fulltext_only("Makes the OPTIMIZE TABLE statement for an InnoDB table process the newly added,deleted,and updated token data for a FULL TEXT index,rather than reorganizing the data in the clustere..","Y"),
	innodb_page_cleaners("Number of page cleaner threads","N"),
	innodb_page_size("Specifies the page size for all InnoDB tablespaces in an instance","N"),
	innodb_parallel_read_threads("","Y"),
	innodb_print_all_deadlocks("During shutdown,prints information about all InnoDB deadlocks to the server error log","Y"),
	innodb_print_ddl_logs("Whether or not to print DDL logs to the error log","Y"),
	innodb_purge_batch_size("Specifies the number of InnoDB redo logs taht trigger a purge operation","Y"),
	innodb_purge_rseg_truncate_frequency("The rate at which undo log purge should be invovked as part of the purge action.A value of n invokes undo log purge on every nth iteration of purge invocation.","Y"),
	innodb_purge_threads("Specifies whether the InnoDB purge operation should be performed in one or more separate threads.By default,this operation is part of the InnoDB master thread","N"),
	innodb_random_read_ahead("Enables the random read-ahead technique for optimizing InnoDB I/O","Y"),
	innodb_read_ahead_threshold("The sensitivity of InnoDB liner read-ahead","Y"),
	innodb_read_io_threads("Number of background I/O threads for read prefetch requests","N"),
	innodb_read_only("Starts the server in read-only mode","N"),
	innodb_redo_log_archive_dirs("","Y"),
	innodb_redo_log_capacity("","Y"),
	innodb_redo_log_encrypt("Controls encryption of redo log data for encrypted tablepaces","Y"),
	innodb_replication_delay("The slave server replication thread delay","Y"),
	innodb_rollback_on_timeout("Roll back entire transaction timeout,not just last statement","N"),
	innodb_rollback_segments("Defines how many of the rollback segments in the system tablespace that InnoDB uses within a transaction","Y"),
	innodb_segment_reserve_factor("","Y"),
	innodb_sort_buffer_size("Specifies size of a buffer used for sorting data during ceation of an InnoDB index","N"),
	innodb_spin_wait_delay("The maximum delay between polls for a spin lock","Y"),
	innodb_spin_wait_pause_multiplier("","Y"),
	innodb_stats_auto_recalc("Causes InnoDB to automatically recalculate persistent statistics after the data in a table is changed substantially","Y"),
	innodb_stats_include_delete_marked("Include delete-marked records when calculating persistent InnoDB statistics","Y"),
	innodb_stats_method("Specifies how InnoDB index statistics collection code should treat NULLs","Y"),
	innodb_stats_on_metadata("Enable or disable InnoDB table statistics updates for metadata statements","Y"),
	innodb_stats_persistent("Turns on the InnoDB persistent statistics feature","Y"),
	innodb_stats_persistent_sample_pages("Number of pages to sample in each InnoDB index,when the persistent statistics feature is also enabled","Y"),
	innodb_stats_transient_sample_pages("Number of pages to sample in each InnoDB index,when the persistent statistics feature is turned off(the default setting)","Y"),
	innodb_status_output("Used to enable or disable periodic output for the standard InnoDB Monitor.Also used in combination with innodb_status_output_locks to enable and disable periodic output for the InnoDB Lock Monitor","Y"),
	innodb_status_output_locks("Used to enable or disable periodic output for the standard InnoDB Monitor. innodb_status_output must also be enabled to produce periodic output for the InnoDB Lock Monitor","Y"),
	innodb_strict_mode("Whether InnoDB returns errors rather than warnings for exceptional conditions","Y"),
	innodb_sync_array_size("Slipts an internal data structure used to coordinate threads,for higher concurrency in workloads with large number of waiting threads","N"),
	innodb_sync_spin_loops("Count of spin-loop rounds in InnoDB mutexes","Y"),
	innodb_table_locks("Enable InnoDB locking in LOC TABLES","Y"),
	innodb_temp_data_file_path("Path to temporary tablespace data files and their sizes","N"),
	innodb_temp_tablespaces_dir("","N"),
	innodb_thread_concurrency("Sets the maximum number of threads allowed inside InnoDB.Value 0 disables the thread throttling","Y"),
	innodb_thread_sleep_delay("Time,in microseconds,that an InnoDB thread sleeps before joining InnoDB queue.Value 0 disables the sleep behaviour","Y"),
	innodb_tmpdir("The directory loation for the temporary table files created during online ALTER TABLE operations","Y"),
	innodb_undo_directory("The relative or absolute directory path where InnoDB creates separate tablespaces for the undo logs;typically used to place those logs on a different storage device","N"),
	innodb_undo_log_encrypt("Controls encryption of undo log data for encrypted tablepaces","Y"),
	innodb_undo_log_truncate("Enable this option to mark the InnoDB undo tablespace for truncation","Y"),
	innodb_undo_tablespaces("The number of tablespace files that rollback segments are divided between","Y"),
	innodb_use_fdatasync("","Y"),
	innodb_use_native_aio("Specifies whether to use the Linux asynchronous I/O subsystem","N"),
	innodb_validate_tablespace_paths("","N"),
	innodb_version("The version of InnoDB","N"),
	innodb_write_io_threads("Number of background I/O threads for writing dirty pages from the buffer cache to disk","N"),
	interactive_timeout("Number of seconds the server waits for activity on an interactive connection before closing it","Y"),
	internal_tmp_mem_storage_engine("Defines the storage to use for internal in-memory temporary tables","Y"),
	join_buffer_size("SIze of buffer that is used for full joins","Y"),
	keep_files_on_create("Do not overwrite existing .MYD/.MYI files in default database directory","Y"),
	key_buffer_size("Size of buffer used for index blocks for MyISAM tables","Y"),
	key_cache_age_threshold("This characteristics the number of hits a hot block has to be untouched until it is considered aged enough to be downgraded to a warm block.This specifies the percentage ratio of that number..","Y"),
	key_cache_block_size("The default size of key cache blocks","Y"),
	key_cache_division_limit("The minimum percentage of warm blocks in key cache","Y"),
	keyring_operations("Whether keyring operations are enabled","Y"),
	large_files_support("Whether large files are supported","N"),
	large_page_size("Size of memory pages when large page support is enabled","N"),
	large_pages("Enable support for large pages","N"),
	lc_messages("Locale for error messages","Y"),
	lc_messages_dir("Directory where error messages are installed","N"),
	lc_time_names("The locale that controls the language used to display day and month names","Y"),
	license("Type of license for the server","N"),
	local_infile("Whether LOCAL is supported for LOAD DATA INFILE statements.Default can be overridden by a number of server and client settings,see text for more information","Y"),
	lock_wait_timeout("Timeout for metadata locks","Y"),
	log_bin("Whether the binary log is enabled","N"),
	log_bin_basename("Path and base name for binary log files","N"),
	log_bin_index("Path and base name for binary log index file","N"),
	log_bin_trust_function_creators("If equal to 0(the default),then when --log-bin is used,creation of a stored function is allowed only to users having the SUPER privilege and only if the function created does not break binary..","Y"),
	log_bin_use_v1_row_events("Shows whether server is using version 1 binary log row events","Y"),
	log_error("Error log file","N"),
	log_error_services("Components to use for error logging","Y"),
	log_error_suppression_list("","Y"),
	log_error_verbosity("Error logging verbosity level","Y"),
	log_output("The destination for general query log and slow query log output","Y"),
	log_queries_not_using_indexes("Log queries that are executed without benefit of any index to the slow query if it is open","Y"),
	log_raw("","Y"),
	log_replica_updates("","N"),
	log_slave_updates("Whether the slave should log the updates performed by its SQL thread to its own binary log.Read-only;set using the --log-slave-updates server option.","N"),
	log_slow_admin_statements("Log slow OPTIMIZE,ANALYZE,ALTER and other administrative statements to the slow query log if it is open","Y"),
	log_slow_extra("","Y"),
	log_slow_replica_statements("","Y"),
	log_slow_slave_statements("Cause slow statements are executed by the slave to be written to the slow query log","Y"),
	log_statements_unsafe_for_binlog("Disables error 1592 warnings being written to the error log","Y"),
	log_throttle_queries_not_using_indexes("Throttle write rate to slow log for queries not using indexes slow query log if it is open","Y"),
	log_timestamps("Log timestamp format","Y"),
	long_query_time("Log all queries that have taken more than long_query_time seconds to execute to file","Y"),
	low_priority_updates("INSERT/DELETE/UPDATE has lower priority than selects","Y"),
	lower_case_file_system("This variable describes the case sensitivity of the file names on the file system","N"),
	lower_case_table_names("If set to 1,table names are stored in lowercase on disk and table names will be case insensitive.Should be set to 2 if you are using a case-insensitive file system.","N"),
	mandatory_roles ("Automatically granted roles for all users","Y"),
	master_info_repository("Whether to write master status information and replication I/O thread location in the master's binary logs to a file or table","Y"),
	master_verify_checksum("Cause master to read checksums from binary log","Y"),
	max_allowed_packet("Max packet length to send to/receive from server","Y"),
	max_binlog_cache_size("Can be used to restrict the total size used to cache a multi-statement transaction","Y"),
	max_binlog_size("Binary log will be rotated automatically when size exceeds this value","Y"),
	max_binlog_stmt_cache_size("Can be used to restrict the total size used to cache all nontransactional statements during a transaction","Y"),
	max_connect_errors("Number of interrupted connection from a host before this host is blocked from further connections","Y"),
	max_connections("Number of simultaneous clients allowed","Y"),
	max_delayed_threads("Do not start more than this number of threads to handle INSERT DELAYED statements.If set to zero,which means INSERT DELAYED is not used","Y"),
	max_digest_length("The maximum digest size in bytes","N"),
	max_error_count("Max number of errors/warnings to store for a statement","1"),
	max_execution_time("Statement execution timeout value","Y"),
	max_heap_table_size("Do not allow creation of heap tables bigger than this","Y"),
	max_insert_delayed_threads("This variable is a synonym for max_delayed_threads","Y"),
	max_join_size("Joins that are probably going to read more than max_join_size records return an error","Y"),
	max_length_for_sort_data("Max number of bytes in sorted records","Y"),
	max_points_in_geometry("Maximum number of points in geometry values for ST_Buffer_Strategy()","Y"),
	max_prepared_stmt_count("Maximum number of prepared statements in the server","Y"),
	max_relay_log_size("If nonzero,relay log is rotated automatically when its size exceeds this value.If zero,size at which rotation occurs is determined by the value of max_binlog_size","Y"),
	max_seeks_for_key("Limit assumed max number of seeks when looking up rows based on a key","Y"),
	max_sort_length("Number of bytes to use when sorting data values","Y"),
	max_sp_recursion_depth("Maximum stored procedures recursion depth","Y"),
	max_user_connections("The maximum number of active connections for a single user(0=no limit)","Y"),
	max_write_lock_count("After this many write locks,allow some read locks to run in between","Y"),
	min_examined_row_limit("Queries examining fewer than this number of rows are not logged to slow query log","Y"),
	myisam_data_pointer_size("Default pointer size to be used for MyISAM tables","Y"),
	myisam_max_sort_file_size("Do not use the fast sort index method to create index if thr temporary file would get bigger than this","Y"),
	myisam_mmap_size("The maximum amount of memory to use for memory mapping compressed MyISAM files","N"),
	myisam_recover_options("The value of the --myisam-recover option","N"),
	myisam_sort_buffer_size("The buffer allocated when sortimg the index for a REPAIR TABLE or when creating indexes for CREATE INDEX or ALTER TABLE","Y"),
	myisam_stats_method("Specifies how MyISAM index statistics collection code should treat NULLs","Y"),
	myisam_use_mmap("Use memory mapping for reading and writing MyISAM tables","Y"),
	mysql_native_password_proxy_users("Whether the mysql_native_password authentication plugin does proxying","Y"),
	mysqlx_bind_address("The network address uses for connections","N"),
	mysqlx_compression_algorithms("","Y"),
	mysqlx_connect_timeout("How long waits for a connect packet.","Y"),
	mysqlx_deflate_default_compression_level("","Y"),
	mysqlx_deflate_max_client_compression_level("","Y"),
	mysqlx_document_id_unique_prefix("Use a custom prefix for document IDs","Y"),
	mysqlx_enable_hello_notice("","Y"),
	mysqlx_idle_worker_thread_timeout("Number of seconds after which an idle worker thread is terminated.","Y"),
	mysqlx_interactive_timeout("Number of seconds to wait for an interactive client to timeout","Y"),
	mysqlx_lz4_default_compression_level("","Y"),
	mysqlx_lz4_max_client_compression_level("","Y"),
	mysqlx_max_allowed_packet("Maximum size of a network packet that can be received by X Plugin.","Y"),
	mysqlx_max_connections("Maximum number of concurrent client connections","Y"),
	mysqlx_min_worker_threads("Minimum number of worker threads used for handling client requests","Y"),
	mysqlx_port("Port where accepts connections","N"),
	mysqlx_port_open_timeout("Time which the X Plugin waits when accepting connections","N"),
	mysqlx_read_timeout("Number of seconds to wait for blocking read operations to complete","Y"),
	mysqlx_socket("Path to the socket where listens for connections","N"),
	mysqlx_ssl_ca ("Path to SSL Certificate Authority file","N"),
	mysqlx_ssl_capath("SSL Certificate Authority file directory","N"),
	mysqlx_ssl_cert("Path to X509 certificate","N"),
	mysqlx_ssl_cipher ("","N"),
	mysqlx_ssl_crl ("Certificate revocation list","N"),
	mysqlx_ssl_crlpath("Certificate revocation list path","N"),
	mysqlx_ssl_key("Path to X509 key","N"),
	mysqlx_wait_timeout("Number of seconds to wait for activity on a connection","Y"),
	mysqlx_write_timeout("Number of seconds to wait for blocking write operation to complete","Y"),
	mysqlx_zstd_default_compression_level("","Y"),
	mysqlx_zstd_max_client_compression_level("","Y"),
	named_pipe("Whether the server supports connections over named pipes","N"),
	named_pipe_full_access_group("",""),
	net_buffer_length("Buffer length for TCP/IP and socket communication","Y"),
	net_read_timeout("Number of seconds to wait for more data from a connection before aborting the read","Y"),
	net_retry_count("Number of times to retry an interrupted read or write on a communication port before giving up","Y"),
	net_write_timeout("Number of seconds to wait for a block to be written to a connection before aborting the write","Y"),
	//new("Use very new,possibly \'unsafe'\ functions","Y"),
	ngram_token_size("Defines the n-gram token size for the full-text search ngram parser","N"),
	offline_mode("Whether server is offline","Y"),
	old("Cause the server to revert to certain behaviours present in older versions","N"),
	old_alter_table("Use old,nonoptimized alter table","Y"),
	open_files_limit("If this is not 0,then mysqld will use this value to reserve file descriptors to use with setrlimit()","N"),
	optimizer_max_subgraph_pairs("","Y"),
	optimizer_prune_level("Controls the heuristic(s) applied during query optimization to prune less-promising partial plans from the optimizer search space","Y"),
	optimizer_search_depth("Maximum depth of search performed by the query optimizer","Y"),
	optimizer_switch("Enable control over which optimizations to use","Y"),
	optimizer_trace("Control optimizer tracing","Y"),
	optimizer_trace_features("Control optimizer tracing","Y"),
	optimizer_trace_limit("Control optimizer tracing","Y"),
	optimizer_trace_max_mem_size("Control optimizer tracing","Y"),
	optimizer_trace_offset("Control optimizer tracing","Y"),
	parser_max_mem_size("Maximum amount of memory available to parser","Y"),
	partial_revokes("","Y"),
	password_history("Number of password changes required before password reuse","Y"),
	password_require_current("","Y"),
	password_reuse_interval("Number of days elapsed required before password reuse","Y"),
	performance_schema("Whether Performance Schema is enabled","N"),
	performance_schema_accounts_size("Number of rows in the accounts table","N"),
	performance_schema_digests_size("Number of rows in the events_statements_summary_by_digest table","N"),
	performance_schema_error_size("Number of instrumented errors","N"),
	performance_schema_events_stages_history_long_size("Number of rows in the events_stages_history_long table","N"),
	performance_schema_events_stages_history_size("Number of rows per thread in the events_stages_history table","N"),
	performance_schema_events_statements_history_long_size("Number of rows in the events_statements_history_long table","N"),
	performance_schema_events_statements_history_size("Number of rows per thread in the events_statements_history table","N"),
	performance_schema_events_transactions_history_long_size("Number of rows in the events_transactions_history_long table","N"),
	performance_schema_events_transactions_history_size("Number of rows per thread in the events_transactions_history table","N"),
	performance_schema_events_waits_history_long_size("Number of rows in the events_waits_history_long table","N"),
	performance_schema_events_waits_history_size("Number of rows per thread in the events_waits_history table","N"),
	performance_schema_hosts_size("Number of rows in the hosts table","N"),
	performance_schema_max_cond_classes("The maximum number of condition instruments","N"),
	performance_schema_max_cond_instances("The maximum number of instrumented condition objects","N"),
	performance_schema_max_digest_length("The maximum Performance Schema digest size in bytes","N"),
	performance_schema_max_digest_sample_age("The query resample age in seconds","Y"),
	performance_schema_max_file_classes("The maximum number of file instruments","N"),
	performance_schema_max_file_handles("The maximum number of opened file objects","N"),
	performance_schema_max_file_instances("The maximum number of instrumented file objects","N"),
	performance_schema_max_index_stat("Maximum number of indexes to keep statistics for","N"),
	performance_schema_max_memory_classes("The maximum number of memory instruments","N"),
	performance_schema_max_metadata_locks("The maximum number of metadata locks to track","N"),
	performance_schema_max_mutex_classes("The maximum number of mutex instruments","N"),
	performance_schema_max_mutex_instances("The maximum number of instrumented mutex objects","N"),
	performance_schema_max_prepared_statements_instances("Number of rows in the prepared_statements_instances table","N"),
	performance_schema_max_program_instances("The maximum number of stored programs for statistics","N"),
	performance_schema_max_rwlock_classes("The maximum number of rwlock instruments","N"),
	performance_schema_max_rwlock_instances("The maximum number of instrumented rwlock objects","N"),
	performance_schema_max_socket_classes("The maximum number of socket instruments","N"),
	performance_schema_max_socket_instances("The maximum number of instrumented socket objects","N"),
	performance_schema_max_sql_text_length("The maximum number of bytes stored from SQL statements","N"),
	performance_schema_max_stage_classes("The maximum number of stage instruments","N"),
	performance_schema_max_statement_classes("The maximum number of statement instruments","N"),
	performance_schema_max_statement_stack("The maximum stored program nesting for statistics","N"),
	performance_schema_max_table_handles("The maximum number of opened table objects","N"),
	performance_schema_max_table_instances("The maximum number of instrumented table objects","N"),
	performance_schema_max_table_lock_stat("Maximum number of tables to keep lock statistics for","N"),
	performance_schema_max_thread_classes("The maximum number of thread instruments","N"),
	performance_schema_max_thread_instances("The maximum number of instrumented thread objects","N"),
	performance_schema_session_connect_attrs_size("Size of the connection attribute strings buffer per thread","N"),
	performance_schema_setup_actors_size("Number of rows in the setup_actors table","N"),
	performance_schema_setup_objects_size("Number of rows in the setup_objects table","N"),
	performance_schema_show_processlist("","Y"),
	performance_schema_users_size("Number of rows in the users table","N"),
	persist_only_admin_x509_subject("","N"),
	persist_sensitive_variables_in_plaintext("","N"),
	persisted_globals_load("Whether to load persisited configuration settings","N"),
	pid_file("Process ID file used by mysqld_safe","N"),
	plugin_dir("Directory forplugins","N"),
	port("Port number on which to listen for TCP/IP connections","N"),
	preload_buffer_size("Size of buffer that is allocated when preloading indexes","Y"),
	print_identified_with_as_hex("","Y"),
	profiling("Enable or disable statement profiling","Y"),
	profiling_history_size("How many statements to maintain profiling information for","Y"),
	protocol_compression_algorithms("","Y"),
	protocol_version("The version of the client/server protocol used by the MySQL server","N"),
	query_alloc_block_size("Allocation block size for query parsing and execution","Y"),
	query_prealloc_size("Persistent buffer for query parsing and execution","Y"),
	range_alloc_block_size("Allocation block size for storing ranges during optimization","Y"),
	range_optimizer_max_mem_size("Limit on range optimizer memory consumpton","Y"),
	rbr_exec_mode("Allows for switching the server between IDEMPOTENT mode(key and some other errors suppressed) and STRICT mode;STRICT mode is the default","Y"),
	read_buffer_size("Each thread that does a sequential scan for a MyISAM table allocates a buffer of this size for each table it scans","Y"),
	read_only("Prevent client updates except from clients with SUPER","Y"),
	read_rnd_buffer_size("When reading rows from a MyISAM table in sorted order after a sort,the rows are read through this buffer to avoid a disk seeks.If not set,then it is set to the value of record_buffer.","Y"),
	regexp_stack_limit("Regular expression match stack size limit","Y"),
	regexp_time_limit("Regular expression match timeout","Y"),
	relay_log("The location and base name to use for relay logs","N"),
	relay_log_basename("Complete path to relay log,including filename","N"),
	relay_log_index("The name of the relay log index file","N"),
	relay_log_info_file("The name of the file in which the slave records information about the relay logs","N"),
	relay_log_info_repository("Whether to write the replication SQl thread's location in the relay logs to a file or a table","Y"),
	relay_log_purge("Determines whether relay logs are purged","Y"),
	relay_log_recovery("Whether automatic recovery of relay log files from master at startup is enabled;must be enabled for a crash-safe slave","N"),
	relay_log_space_limit("Maximum space to use for all relay logs","N"),
	replica_allow_batching("","Y"),
	replica_checkpoint_group("","Y"),
	replica_checkpoint_period("","Y"),
	replica_compressed_protocol("","Y"),
	replica_exec_mode("","Y"),
	replica_load_tmpdir("","N"),
	replica_max_allowed_packet("","Y"),
	replica_net_timeout("","Y"),
	replica_parallel_type("","Y"),
	replica_parallel_workers("","Y"),
	replica_pending_jobs_size_max("","Y"),
	replica_preserve_commit_order("","Y"),
	replica_skip_errors("","N"),
	replica_sql_verify_checksum("","Y"),
	replica_transaction_retries("","Y"),
	replica_type_conversions ("","Y"),
	replication_optimize_for_static_plugin_config("","Y"),
	replication_sender_observe_commit_only("","Y"),
	report_host("Host name or IP of the slave to be reported to the master during slave registration","N"),
	report_password("An arbitrary password that the slave server should report to the master.Not the same as the password for the MySQL replication user account.","N"),
	report_port("Port for connecting to slave reported to the master during slave registration.","N"),
	report_user("An arbitrary user name that the slave server should report to the master.Not the same as the name used with the MySQL replication user account.","N"),
	require_secure_transport("Whether client connections must use secure transport","Y"),
	rpl_read_size("Set the minimum amount of data in bytes that is read from the binary log files and relay log files","Y"),
	rpl_stop_replica_timeout("","Y"),
	rpl_stop_slave_timeout("Set the number of seconds that STOP SLAVE waits before timing out","Y"),
	schema_definition_cache("Defines the number of schema definition objects that can be kept in the dictionary object cache","Y"),
	secondary_engine_cost_threshold("","Y"),
	secure_file_priv("Limit LOAD DATA, and SELECT... INTO OUTFILE, and LOAD_FILE() to files in specified directory","N"),
	select_into_buffer_size("","Y"),
	select_into_disk_sync("","Y"),
	select_into_disk_sync_delay("","Y"),
	server_id("Uniquely identifies the server instance in the community of replication partners.Required when binary logging is enabled.","Y"),
	server_id_bits("The effective value of server_id if the server was started with the --server-id-bits option set to a nondefault value","Y"),
	server_uuid("The server's globally unique ID, automatically (re)generated at server start","N"),
	session_track_gtids("Enables a tracker which can be configured to track different GTIDs","Y"),
	session_track_schema("Whether to track schema changes","Y"),
	session_track_state_change("Whether to track session state changes","Y"),
	session_track_system_variables("Session variables to track changes for","Y"),
	session_track_transaction_info("","Y"),
	sha256_password_auto_generate_rsa_keys("Whether to autogenerate RSA key-pair files","N"),
	sha256_password_private_key_path("SHA256 authentication plugin private key path name","N"),
	sha256_password_proxy_users("Whether the sha256_password authentication plugin does proxying","Y"),
	sha256_password_public_key_path("SHA256 authentication plugin public key path name","N"),
	shared_memory("Whether the server allows shared-memory connections","N"),
	shared_memory_base_name("The name of shared memory to use for shared-memory connections","N"),
	show_create_table_verbosity("Whether to display ROW_FORMAT in SHOW CREATE TABLE even if it has the default value","Y"),
	show_gipk_in_create_table_and_information_schema("","Y"),
	show_old_temporals("Whether SHOW CREATE TABLE should indicate pre-5.6.4 temporal columns","Y"),
	skip_external_locking("Skip system(external)locking","N"),
	skip_name_resolve("Do not resolve host names.All host names are IPs or 'localhost'","N"),
	skip_networking("Do not allow connection with TCP/IP","N"),
	skip_replica_start("","N"),
	skip_show_database("Do not allow SHOW DATABASE statements","N"),
	skip_slave_start("","N"),
	slave_allow_batching("Turns updating batching on and off for a replication slave","Y"),
	slave_checkpoint_group("Maximum number of transactions processed by a multi-threaded slave before a checkpoint operation is called to update progress status.Not supported by NDB Cluster.","Y"),
	slave_checkpoint_period("Update progress status of multi-threaded slave and flush relay log info to disk after this number of milliseconds.Not supported by NDB Cluster.","Y"),
	slave_compressed_protocol("Use compression on master/slave protocol","Y"),
	slave_exec_mode("Allows for switching the slave thread between IDEMPOTENT mode(key and some other errors suppressed)and STRICT mode;STRICT mode is the default,except for NDB Cluster,where IDE...","Y"),
	slave_load_tmpdir("The location where the slave shoould put its temporary files when replicating a LOAD DATA INFILE statement","N"),
	slave_max_allowed_packet("Maximum size,in bytes,of a packet that can be sent from a replication master to a slave;ovverides max_allowed_packet","Y"),
	slave_net_timeout("Number of seconds to wait for more data from a master/slave connection before aborting the read","Y"),
	slave_parallel_type("Tells the slave to use timestamp information(LOGICAL_CLOCK) or database partioning(DATABASE) to parallelize transactions.","Y"),
	slave_parallel_workers("Number of applier threads for executing replication transactions in parallel.A value of 0 disables slave multi-threading.NOt supported by MySQL Cluster.","Y"),
	slave_pending_jobs_size_max("Maximum size of slave worker queues holding events not yet applied","Y"),
	slave_preserve_commit_order("Ensures that all commits by slave workers queues happen in the same order a son the master to maintain consistency when using parallel applier threads.","Y"),
	slave_rows_search_algorithms("Determines search algorithms used for slave update batching.Any 2 or 3 from the list INDEX_SEARCH,TABLE_SCAN,HASH_SCAN.","Y"),
	slave_skip_errors("Tells the slave thread to continue replication when a query returns an error from the provided list","N"),
	slave_sql_verify_checksum("Cause slave to examine checksums when reading from relay log","Y"),
	slave_transaction_retries("Number of times the slave SQL thread will retry a transaction in case it failed with a deadlock or elapsed lock wait timeout,before giving up and stopping","Y"),
	slave_type_conversions("Controls type conversion mode on replication slave.Value is a list of zero or more elements from the list:ALL_LOSSY,ALL_NON_LOSSy.Set to an empty string to disallow type conversions between..","Y"),
	slow_launch_time("IF creating the thread takes longer than this value(in seconds),the Slow_launch_threads counter will be incremented","Y"),
	slow_query_log("Enable|disable slow query log","Y"),
	slow_query_log_file("Name of the slow query log file","Y"),
	socket("Socket file on which to listen for Unix socket or Windows named pipe connections","N"),
	sort_buffer_size("Each thread that needs to do a sort allocates a buffer of this size","Y"),
	source_verify_checksum("","Y"),
	sql_auto_is_null("If set to 1,you can find the last inserted row for a table that contains an AUTO_INCREMENT column by using the following construct:WHERE auto_increment_column IS NULL","Y"),
	sql_big_selects("If set to 0,MySQL aborts SELECT statements that are likely to take a very long time to execute","Y"),
	sql_buffer_result("Forces the result to be put into a temporary table","Y"),
	sql_generate_invisible_primary_key("","Y"),
	sql_log_off("If set to 1,no logging is done to the general query log for this client","Y"),
	sql_mode("Set the SQL server mode","Y"),
	sql_notes("If set to 1,warnings of Note level are recorded","Y"),
	sql_quote_show_create("If set to 1 the server quotes identifiers for SHOW CREATE TABLE and SHOW CREATE DATABASE statements","Y"),
	sql_replica_skip_counter("","Y"),
	sql_require_primary_key("","Y"),
	sql_safe_updates("If set to 1,MySQL aborts UPDATE or DELETE statements that do not use a key in the WHERE clause or a LIMIT clause","Y"),
	sql_select_limit("The maximum number of rows to return from SELECT statements","Y"),
	sql_slave_skip_counter("Number of events from the master that a slave server should skip.Not compatible with GTID replication.","Y"),
	sql_warnings("This variable controls whether single-row INSERT statements produce n information string if warnings occur","Y"),
	ssl_ca("File that contains list of trusted SSL Certificate Authorities","Y"),
	ssl_capath("Directory that contains trusted SSL Certificate Authorityy certificate files","Y"),
	ssl_cert("File that contains X509 certificate","Y"),
	ssl_cipher("List of permitted ciphers for connection encryption","Y"),
	ssl_crl ("File that contains certificate revocation lists","Y"),
	ssl_crlpath("Directory that contains certificate revocation list files","Y"),
	ssl_fips_mode("Whether to enable FIPS mode on the server side","N"),
	ssl_key("File that contains X509 key","Y"),
	ssl_session_cache_mode("","Y"),
	ssl_session_cache_timeout("","Y"),
	stored_program_cache("Sets a \"soft\" upper limit for number of cached stored routines per connection.Stored procedures and stored functions are cached separately;this variable sets size for both of these.","Y"),
	stored_program_definition_cache("Defines the number of stored program and event definition objects that can be kept in the dictionary object cache","Y"),
	super_read_only("Whether to ignore SUPER exceptions to read-only mode","Y"),
	sync_binlog("Synchronously flush binary log to disk after every #th event","Y"),
	sync_master_info("Synchronize master.info to disk after every #th event","Y"),
	sync_relay_log("Synchronize relay log to disk after every #th event","Y"),
	sync_relay_log_info("Synchronize relay.info file to disk after every #th event","Y"),
	sync_source_info("","Y"),
	system_time_zone("The server system time zone","N"),
	table_definition_cache("Number of table definitions that can be stored in the definiton cache","Y"),
	table_encryption_privilege_check("","Y"),
	table_open_cache("Number of open tables for all threads","Y"),
	table_open_cache_instances("Number of open tables cache instances","N"),
	tablespace_definition_cache("Defines the number of tablespace definition objects that can be kept in the dictionary object cache","Y"),
	temptable_max_mmap("","Y"),
	temptable_max_ram("Defines the maximum amount of memory that can occupied by the TempTable storage engine before data is stored on disk","Y"),
	temptable_use_mmap("","Y"),
	terminology_use_previous("","Y"),
	thread_cache_size("How many threads we should keep in a cache for reuse","Y"),
	thread_handling("The thread-handling model","N"),
	thread_stack("The stack size for each thread","N"),
	time_zone("The current time zone","Y"),
	tls_ciphersuites("","Y"),
	tls_version("Protocols permitted for encrypted connections","Y"),
	tmp_table_size("If an in-memory temporary table exceeds this size,MySQL will automatically convert it to an on-disk MyISAM table","Y"),
	tmpdir("Path for temporary files","N"),
	transaction_alloc_block_size("Allocation block size for transactions to be stored in binary log","Y"),
	transaction_isolation("Default transaction isolation level","Y"),
	transaction_prealloc_size("Persistent buffer for transactions to be stored in binary log","Y"),
	transaction_read_only("Default transaction access mode","Y"),
	transaction_write_set_extraction("Define the algorithm used to hash the writes extracted during a transaction","Y"),
	unique_checks("If set to 1(the default),uniqueness checks for secondary indexes in InnoDB tables are performed","Y"),
	updatable_views_with_limit("This variable controls whether updates to a view can be made when the view does not contain all columns of the primary key","Y"),
	version("Output version information and exit","N"),
	version_comment("This variable contains the value of the --with-comment option specified when building MySQL","N"),
	version_compile_machine("The type of machine or architecture on which MySQL was built","N"),
	version_compile_os("The type of operating system on which MySQL was built","N"),
	version_compile_zlib("Version of compiled-inzlib library","N"),
	wait_timeout("Number of secoonds the server waits for activity on a connection before closing it","Y"),
	windowing_use_high_precision("Whether to compute window functions to high precision","Y"),
	xa_detach_on_prepare("","Y"),
	
	
	
	//status variables	
	Aborted_clients ("Number of connections that were aborted because the client died without closing the connection properly.", "N"),
	Aborted_connects ("Number of failed attempts to connect to the MySQL server ", "N"),
	Acl_cache_items_count ("Number of cached privilege objects", "N"),
	Binlog_cache_disk_use ("Number of transactions that used the temporary file instead of the binary log cache ", "N"),
	Binlog_cache_use (" Number of transactions that used the temporary binary log cache ", "N"),
	Binlog_stmt_cache_disk_use ("Number of nontransactional statements that used the temporary file instead of the binary log statement cache", "N"),
	Binlog_stmt_cache_use ("Number of statements that used the temporary binary log statement cache ", "N"),
	Bytes_received ("Number of bytes received from all clients. ", "N"),
	Bytes_sent ("Number of bytes sent to all clients ", "N"),
	Caching_sha2_password_rsa_public_key ("The public key used by the caching_sha2_password authentication plugin for RSA key pair-based password exchange. ", "N"),
	Com_admin_commands ("Count of admin statements ", "N"),
	Com_assign_to_keycache ("Count of CACHE INDEX statements", "N"),
	Com_alter_db ("Count of ALTER DATABASE statements", "N"),
	Com_alter_event ("Count of ALTER EVENT statements", "N"),
	Com_alter_function ("Count of ALTER FUNCTION statements", "N"),
	Com_alter_instance (" ", "N"),
	Com_alter_procedure ("Count of ALTER PROCEDURE statements", "N"),
	Com_alter_resource_group ("Count of ALTER RESOURCE GROUP statements", "N"),
	Com_alter_server ("Count of ALTER SERVER statements", "N"),
	Com_alter_table ("Count of ALTER TABLE statements", "N"),
	Com_alter_tablespace ("Count of ALTER TABLESPACE statements", "N"),
	Com_alter_user ("Count of ALTER USER statements", "N"),
	Com_alter_user_default_role ("Count of ALTER USER ... DEFAULT ROLE statements", "N"),
	Com_analyze ("Count of ANALYZE statements", "N"),
	Com_begin ("Count of BEGIN statements", "N"),
	Com_binlog ("Count of BINLOG statements", "N"),
	Com_call_procedure ("Number of calls to stored procedures", "N"),
	Com_change_db ("Count of CHANGE DATABASE statements", "N"),
	Com_change_master ("Count of CHANGE MASTER TO statements", "N"),
	Com_change_repl_filter ("Count of CHANGE RELICATION FILTER statements", "N"),
	Com_change_replication_source (" ", "N"),
	Com_check ("Count of CHECK statements", "N"),
	Com_checksum ("Count of CHECKSUM statements", "N"),
	Com_clone (" ", "N"),
	Com_commit ("Count of COMMIT statements", "N"),
	Com_create_db ("Count of CREATE DATABASE statements", "N"),
	Com_create_event ("Count of CREATE EVENT statements", "N"),
	Com_create_function ("Count of CREATE FUNCTION statements", "N"),
	Com_create_index ("Count of CREATE INDEX statements", "N"),
	Com_create_procedure ("Count of CREATE PROCEDURE statements", "N"),
	Com_create_role ("Count of CREATE ROLE statements", "N"),
	Com_create_server ("Count of CREATE SERVER statements", "N"),
	Com_create_table ("Count of CREATE TABLE statements", "N"),
	Com_create_resource_group ("Count of CREATE RESOURCE GROUP statements", "N"),
	Com_create_trigger ("Count of CREATE TRIGGER statements", "N"),
	Com_create_udf ("Count of CREATE FUNCTION(UDF) statements", "N"),
	Com_create_user ("Count of CREATE USER statements", "N"),
	Com_create_view ("Count of CREATE VIEW statements", "N"),
	Com_create_spatial_reference_system (" ", "N"),
	Com_dealloc_sql (" Count of DEALLOCATE PREPARE statements", "N"),
	Com_delete ("Count of DELETE statements", "N"),
	Com_delete_multi ("Count of multiple table DELETE statements", "N"),
	Com_do ("Count of DO statements", "N"),
	Com_drop_db ("Count of DROP DATABASE statements", "N"),
	Com_drop_event ("Count of DROP EVENT statements", "N"),
	Com_drop_function ("Count of DROP FUNCTION statements", "N"),
	Com_drop_index ("Count of DROP INDEX statements", "N"),
	Com_drop_procedure ("Count of DROP PROCEDURE statements", "N"),
	Com_drop_resource_group ("Count of DROP RESOURCE GROUP statements", "N"),
	Com_drop_role ("Count of DROP ROLE statements", "N"),
	Com_drop_server ("Count of DROP SERVER statements", "N"),
	Com_drop_spatial_reference_system (" ", "N"),
	Com_drop_table ("Count of DROP TABLE statements", "N"),
	Com_drop_trigger ("Count of DROP TRIGGER statements", "N"),
	Com_drop_user ("Count of DROP USER statements", "N"),
	Com_drop_view ("Count of DROP_VIEW statements", "N"),
	Com_empty_query ("Count of empty statements", "N"),
	Com_execute_sql ("Count of EXECUTE statements", "N"),
	Com_explain_other ("Count of EXPLAIN FOR CONNECTION statements", "N"),
	Com_flush ("Count of FLUSH statements", "N"),
	Com_get_diagnostics ("Count of GET DIAGNOSTICS statements", "N"),
	Com_grant ("Count of GRANT statements", "N"),
	Com_grant_roles ("Count of GRANT ROLE statements", "N"),
	Com_ha_close ("Count of HANDLER CLOSE statements", "N"),
	Com_ha_open ("Count of HANDLER OPEN statements", "N"),
	Com_ha_read ("Count of HANDLER READ statements", "N"),
	Com_help ("Count of HELP statements", "N"),
	Com_import (" ", "N"),
	Com_insert ("Count of INSERT statements", "N"),
	Com_insert_select ("Count of INSERT SELECT statements", "N"),
	Com_install_component ("Count of INSTALL COMPONENT statements", "N"),
	Com_install_plugin ("Count of INSTALL PLUGIN statements", "N"),
	Com_kill ("Count of KILL statements", "N"),
	Com_load ("Count of LOAD statements", "N"),
	Com_lock_instance (" ", "N"),
	Com_lock_tables ("Count of LOCK TABLES statements", "N"),
	Com_optimize ("Count of OPTIMIZE statements", "N"),
	Com_preload_keys ("Count of PRELOAD KEYS statements", "N"),
	Com_prepare_sql ("Count of PREPARE statements", "N"),
	Com_purge ("Count of PURGE statements", "N"),
	Com_purge_before_date ("Count of PURGE BEFORE DATE statements", "N"),
	Com_release_savepoint ("Count of RELEASE SAVEPOINT statements", "N"),
	Com_rename_table ("Count of RENAME TABLE statements", "N"),
	Com_rename_user ("Count of RENAME USER statements", "N"),
	Com_repair ("Count of REPAIR statements", "N"),
	Com_replace ("Count of REPLACE statements", "N"),
	Com_replace_select ("Count of REPLACE SELECT statements", "N"),
	Com_reset ("Count of RESET statements", "N"),
	Com_resignal ("Count of RESIGNAL statements", "N"),
	Com_restart (" ", "N"),
	Com_revoke ("Count of REVOKE statements that revoke roles", "N"),
	Com_revoke_all ("Count of REVOKE ALL statements", "N"),
	Com_revoke_roles ("Count of REVOKE ROLES statements", "N"),
	Com_rollback ("Count of ROLLBACK statements", "N"),
	Com_rollback_to_savepoint ("Count of ROLLBACK TO SAVEPOINT statements", "N"),
	Com_savepoint ("Count of SAVEPOINT statements", "N"),
	Com_select ("Count of SELECT statements", "N"),
	Com_set_option ("Count of SET OPTION statements", "N"),
	Com_set_password (" ", "N"),
	Com_set_resource_group ("Count of SET RESOURCE GROUP statements", "N"),
	Com_set_role ("Count of SET ROLE statements", "N"),
	Com_signal ("Count of SIGNAL statements", "N"),
	Com_show_binlog_events ("Count of SHOW BINLOG EVENTS statements", "N"),
	Com_show_binlogs ("Count of SHOW BINLOGS statements", "N"),
	Com_show_charsets ("Count of SHOW CHARSET statements", "N"),
	Com_show_collations ("Count of SHOW COLLATION statements", "N"),
	Com_show_create_db ("Count of SHOW CREATE DATABASE statements", "N"),
	Com_show_create_event ("Count of SHOW CREATE EVENT statements", "N"),
	Com_show_create_func ("Count of SHOW CREATE FUNCTION statements", "N"),
	Com_show_create_proc ("Count of SHOW CREATE PROCEDURE statements", "N"),
	Com_show_create_table ("Count of SHOW CREATE TABLE statements", "N"),
	Com_show_create_trigger ("Count of SHOW CREATE TRIGGER statements", "N"),
	Com_show_databases ("Count of SHOW DATABASES statements", "N"),
	Com_show_engine_logs ("Count of SHOW ENGINE LOGS statements", "N"),
	Com_show_engine_mutex ("Count of SHOW ENGINE MUTEX statements", "N"),
	Com_show_engine_status ("Count of SHOW ENGINE STATUS statements", "N"),
	Com_show_events ("Count of SHOW EVENTS statements", "N"),
	Com_show_errors ("Count of SHOW ERRORS statements", "N"),
	Com_show_fields ("Count of SHOW FIELDS statements", "N"),
	Com_show_function_code ("Count of SHOW FUNCTION CODE statements", "N"),
	Com_show_function_status ("Count of SHOW FUNCTION STATUS statements", "N"),
	Com_show_grants ("Count of SHOW GRANTS statements", "N"),
	Com_show_keys ("Count of SHOW KEYS statements", "N"),
	Com_show_master_status ("Count of SHOW MASTER STATUS statements", "N"),
	Com_show_open_tables ("Count of SHOW OPEN TABLES statements", "N"),
	Com_show_plugins ("Count of SHOW PLUGINS statements", "N"),
	Com_show_privileges ("Count of SHOW PRIVILEGES statements", "N"),
	Com_show_procedure_code ("Count of SHOW PROCEDURE CODE statements", "N"),
	Com_show_procedure_status ("Count of SHOW PROCEDURE STATUS statements", "N"),
	Com_show_processlist ("Count of SHOW PROCESSLIST statements", "N"),
	Com_show_profile ("Count of SHOW PROFILE statements", "N"),
	Com_show_profiles ("Count of SHOW PROFILES statements", "N"),
	Com_show_relaylog_events ("Count of SHOW RELAYLOG EVENTS statements", "N"),
	Com_show_replicas (" ", "N"),
	Com_show_slave_hosts ("Count of SHOW SLAVE HOSTS statements", "N"),
	Com_show_replica_status (" ", "N"),
	Com_show_slave_status ("Count of SHOW SLAVE STATUS statements", "N"),
	Com_show_status ("Count of SHOW STATUS statements", "N"),
	Com_show_storage_engines ("Count of SHOW STORAGE ENGINES statements", "N"),
	Com_show_table_status ("Count of SHOW TABLE STATUS statements", "N"),
	Com_show_tables ("Count of SHOW TABLES statements", "N"),
	Com_show_triggers ("Count of SHOW TRIGGERS statements", "N"),
	Com_show_variables ("Count of SHOW VARIABLES statements", "N"),
	Com_show_warnings ("Count of SHOW WARNINGS statements", "N"),
	Com_show_create_user ("Count of SHOW CREATE USER statements", "N"),
	Com_shutdown ("Count of SHUTDOWN statements", "N"),
	Com_replica_start (" ", "N"),
	Com_slave_start ("Count of START SLAVE statements", "N"),
	Com_replica_stop (" ", "N"),
	Com_slave_stop ("Count of STOP SLAVE statements", "N"),
	Com_group_replication_start ("Count of START GROUP_REPLICATION statements", "N"),
	Com_group_replication_stop ("Count of STOP GROUP_REPLICATION statements", "N"),
	Com_stmt_execute ("Count of STATEMENT EXECUTE statements", "N"),
	Com_stmt_close ("Count of STATEMENT CLOSE statements", "N"),
	Com_stmt_fetch ("Count of STATEMENT FETCH statements", "N"),
	Com_stmt_prepare ("Count of STATEMENT PREPARE statements", "N"),
	Com_stmt_reset ("Count of STATEMENT RESET statements", "N"),
	Com_stmt_send_long_data ("Count of STATEMENT SEND LONG DATA statements", "N"),
	Com_truncate ("Count of TRUNCATE statements", "N"),
	Com_uninstall_component ("Count of UNINSTALL COMPONENT statements", "N"),
	Com_uninstall_plugin ("Count of UNINSTALL PLUGIN statements", "N"),
	Com_unlock_instance (" ", "N"),
	Com_unlock_tables ("Count of UNLOCK TABLES statements", "N"),
	Com_update ("Count of UPDATE statements", "N"),
	Com_update_multi ("Count of multiple UPDATE statements", "N"),
	Com_xa_commit ("Count of XA COMMIT statements", "N"),
	Com_xa_end ("Count of XA END statements", "N"),
	Com_xa_prepare ("Count of XA PREPARE statements", "N"),
	Com_xa_recover ("Count of XA RECOVER statements", "N"),
	Com_xa_rollback ("Count of XA ROLLBACK statements", "N"),
	Com_xa_start ("Count of XA START statements", "N"),
	Com_stmt_reprepare ("Count of automatic repreparations of prepared statements", "N"),
	Connection_errors_accept ("Number of errors calling accept on the listening port", "N"),
	Connection_errors_internal ("Number of connections refused due to internal errors", "N"),
	Connection_errors_max_connections ("Number of connections refused due to the max_connections limit", "N"),
	Connection_errors_peer_address ("Number of errors searching for connection client IP addresses", "N"),
	Connection_errors_select ("Number of errors calling select/poll on the listening port", "N"),
	Connection_errors_tcpwrap ("Number of connections refused by libwrap", "N"),
	Connections ("Number of connections attempts", "N"),
	Created_tmp_disk_tables ("Number of temporary tables on disk created automatically by the server while executing statements", "N"),
	Created_tmp_files ("How many temporary files mysqld has created", "N"),
	Created_tmp_tables ("How many temporary tables mysqld has created", "N"),
	Current_tls_ca (" ", "N"),
	Current_tls_capath (" ", "N"),
	Current_tls_cert (" ", "N"),
	Current_tls_cipher (" ","N" ), 
	Current_tls_ciphersuites (" ", "N"), 
	Current_tls_crl (" ", "N"), 
	Current_tls_crlpath ("", "N"), 
	Current_tls_key (" ", "N"), 
	Current_tls_version (" ", "N"), 
	Delayed_errors ("Number of rows written with INSERT DELAYED for which some error occured", "N"), 
	Delayed_insert_threads ("Number of INSERT DELAYED threads handlers in use", "N"), 
	Delayed_writes ("Number of INSERT DELAYED rows written", "N"), 
	Error_log_buffered_bytes (" ", "N"), 
	Error_log_buffered_events (" ", "N"), 
	Error_log_expired_events (" ", "N"), 
	Error_log_latest_write (" ", "N"), 
	Flush_commands ("Number of FLUSH statements executed", "N"), 
	Global_connection_memory (" ", "N"), 
	Handler_commit ("Number of internal COMMIT statements", "N"), 
	Handler_delete ("Number of times that rows have been deleted from tables", "N"), 
	Handler_discover ("Number of times that tables have been discovered", "N"), 
	Handler_external_lock ("Number of locks started while a statement executed", "N"), 
	Handler_mrr_init ("Number of times storage engine MRR implementation is used for table access", "N"), 
	Handler_prepare ("A counter for the prepare phase of two-phase commit operations", "N"), 
	Handler_read_first ("Number of times the first entry in an index was read", "N"), 
	Handler_read_key ("Number of requests to read a row based on a key", "N"), 
	Handler_read_last ("Number of requests to read the last index entry", "N"), 
	Handler_read_next ("Number of request to read the next row in key order", "N"), 
	Handler_read_prev ("Number of request to read the previous row in key order", "N"), 
	Handler_read_rnd ("Number of request to read a row based on a fixed position", "N"), 
	Handler_read_rnd_next ("Number of request to read the next row in the data file", "N"), 
	Handler_rollback ("Number of requests for a storage engine to perform a rollback operation", "N"), 
	Handler_savepoint ("Number of requests for a storage engine to place a savepoint", "N"), 
	Handler_savepoint_rollback ("Number of requests for a storage engine to rollback to a savepoint", "N"), 
	Handler_update (" Number of requests to update a row in a table", "N"), 
	Handler_write (" Number of requests to insert a row in a table", "N"), 
	Innodb_buffer_pool_dump_status ("Display status of buffer pool recording operation triggered by innodb_buffer_pool_dump_at_shutdown or innodb_buffer_pool_dump_now", "N"), 
	Innodb_buffer_pool_load_status ("Display status of buffer pool warmup operation triggered by innodb_buffer_pool_load_at_startup or innodb_buffer_pool_load_now", "N"), 
	Innodb_buffer_pool_resize_status ("The status of the dynamic buffer pool resizing operation", "N"), 
	Innodb_buffer_pool_resize_status_code (" ", "N"), 
	Innodb_buffer_pool_resize_status_progress (" ", "N"), 
	Innodb_buffer_pool_pages_data ("Number of pages containing data(dirty or clean) in the buffer pool", "N"), 
	Innodb_buffer_pool_bytes_data ("Number of bytes containing data(dirty or clean) in the buffer pool", "N"), 
	Innodb_buffer_pool_pages_dirty ("Number of pages currently dirty in the buffer pool", "N"), 
	Innodb_buffer_pool_bytes_dirty ("Number of bytes currently dirty in the buffer pool", "N"), 
	Innodb_buffer_pool_pages_flushed ("Number of bufferpool page-flush requests", "N"), 
	Innodb_buffer_pool_pages_free ("Number of bufferpool pages free", "N"), 
	Innodb_buffer_pool_pages_misc ("Number of pages that are busy because they have been allocated for administrative overhead", "N"), 
	Innodb_buffer_pool_pages_total ("The total size of buffer pool,in pages", "N"), 
	Innodb_buffer_pool_read_ahead_rnd ("Number of random read-aheads initiated by InnoDB", "N"), 
	Innodb_buffer_pool_read_ahead ("Number of pages read by the InnoDB read-ahead thread", "N"), 
	Innodb_buffer_pool_read_ahead_evicted ("Number of read-ahead pages evicted without being accessed", "N"), 
	Innodb_buffer_pool_read_requests ("Number of logical read requests InnoDB has done", "N"), 
	Innodb_buffer_pool_reads ("Number of logical reads that InnoDB could not satisfy from the buffer pool and had to do a single-page read", "N"), 
	Innodb_buffer_pool_wait_free ("Counts number of waits for pages to be flushed", "N"), 
	Innodb_buffer_pool_write_requests ("Number of writes done to the buffer pool", "N"), 
	Innodb_data_fsyncs ("Number of fsync() operations so far", "N"), 
	Innodb_data_pending_fsyncs ("The current number of pending fsync() operations", "N"), 
	Innodb_data_pending_reads ("The current number of pending reads", "N"), 
	Innodb_data_pending_writes ("Number of pending writes", "N"), 
	Innodb_data_read ("The amount of data read so far,in bytes", "N"), 
	Innodb_data_reads ("The total number of data reads", "N"), 
	Innodb_data_writes ("The total number of data writes", "N"), 
	Innodb_data_written ("The amount of data written in bytes", "N"), 
	Innodb_dblwr_pages_written ("Number of doublewrite pages that have been written", "N"), 
	Innodb_dblwr_writes ("Number of doublewrite operations that have been performed", "N"), 
	Innodb_redo_log_read_only (" ", "N"), 
	Innodb_redo_log_uuid (" ", "N"), 
	Innodb_redo_log_checkpoint_lsn (" ", "N"), 
	Innodb_redo_log_current_lsn (" ", "N"), 
	Innodb_redo_log_flushed_to_disk_lsn (" ", "N"), 
	Innodb_redo_log_logical_size (" ", "N"), 
	Innodb_redo_log_physical_size (" ", "N"), 
	Innodb_redo_log_capacity_resized (" ", "N"), 
	Innodb_redo_log_resize_status (" ", "N"), 
	Innodb_log_waits ("Number of times that the log buffer was too small and a wait required for it to be flushed before continuing", "N"), 
	Innodb_log_write_requests ("Number of log write requests", "N"), 
	Innodb_log_writes ("Number of physical writes to the log", "N"), 
	Innodb_os_log_fsyncs ("Number of fsync() writes done to the log file", "N"), 
	Innodb_os_log_pending_fsyncs ("Number of pending log file fsync() operations", "N"), 
	Innodb_os_log_pending_writes ("Number of pending log file writes", "N"), 
	Innodb_os_log_written ("Number of bytes written to the log file", "N"), 
	Innodb_page_size ("The compiled-in InnoDB page size", "N"), 
	Innodb_pages_created ("Number of pages created", "N"), 
	Innodb_pages_read ("Number of pages read", "N"), 
	Innodb_pages_written ("Number of pages written", "N"), 
	Innodb_redo_log_enabled (" ", "N"), 
	Innodb_row_lock_current_waits ("Number of row locks currently being waited for", "N"), 
	Innodb_row_lock_time ("The total time spent in acquiring row locks,in milliseconds", "N"), 
	Innodb_row_lock_time_avg ("The average time to acquiring row locks,in milliseconds", "N"), 
	Innodb_row_lock_time_max ("The maximum time to acquiring row locks,in milliseconds", "N"), 
	Innodb_row_lock_waits ("Number of times a row lock had to be waited for", "N"), 
	Innodb_rows_deleted ("Number of rows deleted from InnoDB tables", "N"), 
	Innodb_rows_inserted ("Number of rows inserted from InnoDB tables", "N"), 
	Innodb_rows_read ("Number of rows read from InnoDB tables", "N"), 
	Innodb_rows_updated ("Number of rows updated from InnoDB tables", "N"), 
	Innodb_system_rows_deleted (" ", "N"), 
	Innodb_system_rows_inserted (" ", "N"), 
	Innodb_system_rows_read (" ", "N"), 
	Innodb_system_rows_updated (" ", "N"), 
	Innodb_sampled_pages_read (" ", "N"), 
	Innodb_sampled_pages_skipped (" ", "N"), 
	Innodb_num_open_files (" Number of physical files currently opened by InnoDB", "N"), 
	Innodb_truncated_status_writes ("Number of times output from the SHOW ENGINE INNODB STATUS statement has been truncated", "N"), 
	Innodb_undo_tablespaces_total (" ", "N"), 
	Innodb_undo_tablespaces_implicit (" ", "N"), 
	Innodb_undo_tablespaces_explicit (" ", "N"), 
	Innodb_undo_tablespaces_active (" ", "N"), 
	Key_blocks_not_flushed ("Number of key blocks in the key cache that have changed but have not yet been flushed to disk", "N"), 
	Key_blocks_unused ("Number of unused blocks in the key cache", "N"), 
	Key_blocks_used ("Number of used blocks in the key cache", "N"), 
	Key_read_requests ("Number of requests to read a key block from the cache", "N"), 
	Key_reads ("Number of physical reads of a key block from disk", "N"), 
	Key_write_requests ("Number of requests to write a key block to the cache", "N"), 
	Key_writes ("Number of physical writes of a key block from disk", "N"), 
	Locked_connects ("Number of attempts to connect to locked accounts", "N"), 
	Max_execution_time_exceeded ("Number of statements that exceeded the execution timeout value", "N"), 
	Max_execution_time_set ("Number of statements for which execution timeout was set", "N"), 
	Max_execution_time_set_failed ("Number of statements for which execution timeout setting failed", "N"), 
	Max_used_connections ("The maximum number of connections that have been in use simultaneously since the server started", "N"), 
	Max_used_connections_time ("The time at which Max_used_connections reached its current value", "N"), 
	Mysqlx_aborted_clients ("Number of clients that were disconnected because of an input or output timeout.", "N"), 
	Mysqlx_address ("The network address X Plugin is bound to", "N"), 
	Mysqlx_bytes_received ("The number of bytes received through the network", "N"), 
	Mysqlx_bytes_received_compressed_payload (" ", "N"), 
	Mysqlx_bytes_received_uncompressed_frame (" ", "N"), 
	Mysqlx_bytes_sent ("The number of bytes sent through the network", "N"), 
	Mysqlx_bytes_sent_compressed_payload (" ", "N"), 
	Mysqlx_bytes_sent_uncompressed_frame (" ", "N"), 
	Mysqlx_compression_algorithm (" ", "N"), 
	Mysqlx_compression_level (" ", "N"), 
	Mysqlx_connection_accept_errors ("The number of connections which have caused accept errors", "N"), 
	Mysqlx_connection_errors ("The number of connections which have been closed", "N"), 
	Mysqlx_connections_accepted ("The number of connections which have been accepted", "N"), 
	Mysqlx_connections_closed ("The number of connections which have been closed", "N"), 
	Mysqlx_connections_rejected ("The number of connections which have been rejected", "N"), 
	Mysqlx_crud_create_view ("The number of create view requests received", "N"), 
	Mysqlx_crud_delete ("The number of delete requests received", "N"), 
	Mysqlx_crud_drop_view ("The number of drop view requests received", "N"), 
	Mysqlx_crud_find ("The number of find requests received", "N"), 
	Mysqlx_crud_insert ("The number of insert requests received", "N"), 
	Mysqlx_crud_modify_view ("The number of modify view requests received", "N"), 
	Mysqlx_crud_update ("The number of update requests received", "N"), 
	Mysqlx_cursor_close (" ", "N"), 
	Mysqlx_cursor_fetch (" ", "N"), 
	Mysqlx_cursor_open (" ", "N"), 
	Mysqlx_errors_sent ("number of errors that were sent to clients", "N"), 
	Mysqlx_errors_unknown_message_type ("The number of unknown message types that have been received", "N"), 
	Mysqlx_expect_close ("The number of expectation blocks closed", "N"), 
	Mysqlx_expect_open ("The number of expectation blocks opened", "N"), 
	Mysqlx_init_error ("The number of errors during initialisation", "N"), 
	Mysqlx_messages_sent (" ", "N"), 
	Mysqlx_notice_global_sent (" ", "N"), 
	Mysqlx_notice_other_sent ("The number of other types of notices sent back to clients", "N"), 
	Mysqlx_notice_warning_sent ("The number of warning notices sent back to clients", "N"), 
	Mysqlx_notified_by_group_replication (" ", "N"), 
	Mysqlx_port ("The port which X Plugin is listening on", "N"), 
	Mysqlx_prep_deallocate (" ", "N"), 
	Mysqlx_prep_execute (" ", "N"), 
	Mysqlx_prep_prepare (" ", "N"), 
	Mysqlx_rows_sent ("The number of rows sent back to clients", "N"), 
	Mysqlx_sessions ("The number of sessions that havae been opened", "N"), 
	Mysqlx_sessions_accepted ("The number of session attempts which have been accepted", "N"), 
	Mysqlx_sessions_closed ("The number of sessions that have been closed", "N"), 
	Mysqlx_sessions_fatal_error ("The number of sessions that have closed with a fatal error", "N"), 
	Mysqlx_sessions_killed ("The number of sessions which have been killed", "N"), 
	Mysqlx_sessions_rejected ("The number of session attempts which have been rejected", "N"), 
	Mysqlx_socket ("The socket which is listening on", "N"),
	Mysqlx_ssl_accepts ("The number of accepted SSL connections", "N"), 
	Mysqlx_ssl_active ("Whether SSL is active", "N"), 
	Mysqlx_ssl_cipher ("The current SSL cipher(empty for non-SSL connections)", "N"), 
	Mysqlx_ssl_cipher_list ("A list of possible SSL ciphers(empty for non-SSL connections)", "N"), 
	Mysqlx_ssl_ctx_verify_depth ("The certificate verification depth limit currently set in ctx", "N"), 
	Mysqlx_ssl_ctx_verify_mode ("The certificate verification mode currently set in ctx", "N"), 
	Mysqlx_ssl_finished_accepts ("The number of successful SSL connections to the server", "N"), 
	Mysqlx_ssl_server_not_after ("The last date for which the SSL certificate is valid", "N"), 
	Mysqlx_ssl_server_not_before ("The first date for which the SSL certificate is valid", "N"), 
	Mysqlx_ssl_verify_depth ("The certificate verification depth for SSL connection", "N"), 
	Mysqlx_ssl_verify_mode ("The certificate verification mode for SSL connection", "N"), 
	Mysqlx_ssl_version ("The name of the protocol used for SSL connection", "N"), 
	Mysqlx_stmt_create_collection ("The number of create collection statements received", "N"), 
	Mysqlx_stmt_create_collection_index ("The number of create collection index statements received", "N"), 
	Mysqlx_stmt_disable_notices ("The number of disable notice statements received", "N"), 
	Mysqlx_stmt_drop_collection ("The number of drop collection statements received", "N"), 
	Mysqlx_stmt_drop_collection_index ("The number of drop collection index statements received", "N"), 
	Mysqlx_stmt_enable_notices ("The number of enable notice statements received", "N"), 
	Mysqlx_stmt_ensure_collection ("Number of executed ensure collection admin commands;incremented on reception of Mysqlx.SQL.StmtExecute with the admin command", "N"), 
	Mysqlx_stmt_execute_mysqlx ("Incremented on reception of each StmtExecute message with namespace set to mysqlx", "N"), 
	Mysqlx_stmt_execute_sql ("The number of StmtExecute requests received for the SQL namespace", "N"), 
	Mysqlx_stmt_execute_xplugin ("The number of StmtExecute requests received for the X Plugin namespace", "N"), 
	Mysqlx_stmt_get_collection_options (" ", "N"), 
	Mysqlx_stmt_kill_client ("The number of kill client statements received", "N"), 
	Mysqlx_stmt_list_clients ("The number of list client statements received", "N"), 
	Mysqlx_stmt_list_notices ("The number of list notice statements received", "N"), 
	Mysqlx_stmt_list_objects ("The number of list object statements received", "N"), 
	Mysqlx_stmt_modify_collection_options (" ", "N"), 
	Mysqlx_stmt_ping ("The number of ping statements received", "N"), 
	Mysqlx_worker_threads ("The number of worker threads available", "N"), 
	Mysqlx_worker_threads_active ("The number of worker threads currently used", "N"), 
	Not_flushed_delayed_rows ("Number of rows waiting to be written in INSERT DELAY queues", "N"), 
	Ongoing_anonymous_transaction_count ("Number of ongoing anonymous transactions", "N"), 
	Open_files ("Number of files that are open", "N"), 
	Open_streams ("Number of streams that are open(used mainly for logging)", "N"), 
	Open_table_definitions ("Number of cached tabe definitions", "N"), 
	Open_tables ("Number of tables that are open", "N"), 
	Opened_files ("Number of files that are opened using my_open()", "N"), 
	Opened_table_definitions ("Number of table definitions that have been cached", "N"), 
	Opened_tables ("Number of tables that have been opened", "N"), 
	Performance_schema_accounts_lost ("How many accounts table rows could not be added", "N"), 
	Performance_schema_cond_classes_lost ("How many condition instruments could not be loaded", "N"), 
	Performance_schema_cond_instances_lost ("How many condition instrument instances could not be created", "N"), 
	Performance_schema_digest_lost ("How many digests could not be instrumented", "N"), 
	Performance_schema_file_classes_lost ("How many file instruments could not be loaded", "N"), 
	Performance_schema_file_handles_lost ("How many file instrument instances could not be opened", "N"), 
	Performance_schema_file_instances_lost ("How many file instrument instances could not be created", "N"), 
	Performance_schema_hosts_lost ("How many hosts table rows could not be added", "N"), 
	Performance_schema_index_stat_lost ("Number of indexes for which statistics were lost", "N"), 
	Performance_schema_locker_lost ("How many events are lost or not recorded", "N"), 
	Performance_schema_memory_classes_lost ("How many memory instruments could not be loaded", "N"), 
	Performance_schema_metadata_lock_lost ("Number of metadata locks that could not be recorded", "N"), 
	Performance_schema_mutex_classes_lost ("How many mutex instruments could not be loaded", "N"), 
	Performance_schema_mutex_instances_lost ("How many mutex instrument instances could not be created", "N"), 
	Performance_schema_nested_statement_lost ("Number of stored program statements for which statistics were lost", "N"), 
	Performance_schema_prepared_statements_lost ("Number of prepared statements that could not be instrumented", "N"), 
	Performance_schema_program_lost ("Number of stored programs for which statistics were lost", "N"), 
	Performance_schema_rwlock_classes_lost ("How many rwlock instruments could not be loaded", "N"), 
	Performance_schema_rwlock_instances_lost ("How many rwlock instrument instances could not be created", "N"), 
	Performance_schema_session_connect_attrs_longest_seen ("The size of the longest valid connection attribute buffer seen", "N"), 
	Performance_schema_session_connect_attrs_lost ("The number of connections for which attribute strings could not be created", "N"), 
	Performance_schema_socket_classes_lost ("How many socket instruments could not be loaded", "N"), 
	Performance_schema_socket_instances_lost ("How many socket instrument instances could not be created", "N"), 
	Performance_schema_stage_classes_lost ("How many stage instruments could not be loaded", "N"), 
	Performance_schema_statement_classes_lost ("How many statement instruments could not be loaded", "N"), 
	Performance_schema_table_handles_lost ("How many table instrument instances could not be opened", "N"), 
	Performance_schema_table_instances_lost ("How many table instrument instances could not be created", "N"), 
	Performance_schema_table_lock_stat_lost ("Number of tables for which lock statistics were lost", "N"), 
	Performance_schema_thread_classes_lost ("How many thread instruments could not be loaded", "N"), 
	Performance_schema_thread_instances_lost ("How many thread instrument instances could not be created", "N"), 
	Performance_schema_users_lost ("How many users table rows could not be added", "N"), 
	Prepared_stmt_count ("The current number of prepared statements", "N"), 
	Queries ("Number of statements executed by the server", "N"), 
	Questions ("Number of statements that clients have sent to the server", "N"), 
	Replica_open_temp_tables (" ", "N"), 
	Resource_group_supported (" ", "N"), 
	Rsa_public_key ("sha256_password authentication plugin RSA public key value", "N"), 
	Secondary_engine_execution_count (" ", "N"), 
	Select_full_join ("Number of joins that perform table scans because they do not use indexes", "N"), 
	Select_full_range_join ("Number of joins that used a range search on a reference table", "N"), 
	Select_range ("Number of joins that used ranges on the first table", "N"), 
	Select_range_check ("Number of joins without keys that check for key usage after each row", "N"), 
	Select_scan ("Number of joins that did a full scan of the first table", "N"), 
	Slave_open_temp_tables ("Number of temporary tables that the slave SQL thread currently has open", "N"), 
	Slow_launch_threads ("Number of threads that have taken more than slow_launch_time seconds to create", "N"), 
	Slow_queries ("Number of quries that have taken more than long_query_time seconds", "N"), 
	Sort_merge_passes ("Number of merge passes that the sort algorithm has had to do", "N"), 
	Sort_range ("Number of sorts that were done using ranges", "N"), 
	Sort_rows ("Number of sorted rows", "N"), 
	Sort_scan ("Number of sorts that were done by scanning the table", "N"), 
	Ssl_accept_renegotiates ("Number of negotiates needed to establish the connection", "N"), 
	Ssl_accepts ("Number of accepted SSL connections", "N"), 
	Ssl_callback_cache_hits ("Number of callback cache hits", "N"),
	Ssl_cipher ("The current SSL cipher", "N"), 
	Ssl_cipher_list ("The list of possible SSL ciphers", "N"), 
	Ssl_client_connects ("Number of SSL connection attempts to an SSL-enabled master", "N"), 
	Ssl_connect_renegotiates ("Number of negotiates needed to establish the connection to an SSL-enabled master", "N"), 
	Ssl_ctx_verify_depth ("The SSL context verification depth(how many certificates in the chain are tested)", "N"), 
	Ssl_ctx_verify_mode ("The SSL context verification mode", "N"), 
	Ssl_default_timeout ("The default SSL timeout", "N"), 
	Ssl_finished_accepts ("Number of successful SSL connections to the server", "N"), 
	Ssl_finished_connects ("Number of successful slave connections to an SSL-enabled master", "N"), 
	Ssl_server_not_after ("SSL certificate last valid date", "N"), 
	Ssl_server_not_before ("SSL certificate first valid date", "N"), 
	Ssl_session_cache_hits ("Number of SSL session cache hits", "N"), 
	Ssl_session_cache_misses ("Number of SSL session cache misses", "N"), 
	Ssl_session_cache_mode ("The SSL session cache mode", "N"), 
	Ssl_session_cache_overflows ("Number of SSL session cache overflows", "N"), 
	Ssl_session_cache_size ("The SSL session cache size", "N"), 
	Ssl_session_cache_timeout (" ", "N"), 
	Ssl_session_cache_timeouts ("Number of SSL session cache timeouts", "N"), 
	Ssl_sessions_reused ("How many SSL connections were reused from the cache", "N"), 
	Ssl_used_session_cache_entries ("How many SSL session cache were used", "N"), 
	Ssl_verify_depth ("The verification depth for replication SSL coonnections", "N"), 
	Ssl_verify_mode ("The verification mode for replication SSL coonnections", "N"), 
	Ssl_version ("The SSL version number", "N"), 
	Table_locks_immediate ("Number of times that a table lock was acquired immediately", "N"), 
	Table_locks_waited ("Number of times that a table lock could not be acquired immediately and a wait was needed", "N"), 
	Table_open_cache_hits ("Number of hits for open tables cache lookups", "N"), 
	Table_open_cache_misses ("Number of misses for open tables cache lookups", "N"), 
	Table_open_cache_overflows ("Number of overflows for open tables cache", "N"), 
	Tc_log_max_pages_used ("When the memory-mapped implementation of the log that is used by mysqld acts as the transaction coordinator for recovery of internal XA transactions,this variable indicates the largest number of..", "N"), 
	Tc_log_page_size ("The page sie used for the memory-mapped implementation of the XA recovery log", "N"), 
	Tc_log_page_waits ("For the memory-mapped implementation of the recovery log,this variable increments each time the server was not able to commit a transaction and had to wait for a free page in the log", "N"), 
	Telemetry_traces_supported (" ", "N"), 
	Threads_cached ("Number of threads in the thread cache", "N"), 
	Threads_connected ("Number of currently open connections", "N"), 
	Threads_created ("Number of threads created to handle connections", "N"), 
	Threads_running ("Number of threads that are not sleeping", "N"), 
	Tls_library_version (" ", "N"), 
	Uptime ("Number of seconds the server has been up", "N"), 
	Uptime_since_flush_status ("Number of seconds since the most recent FLUSH STATUS", "N");	


	
	private String description;
	private String isEditable;
	
	MySQLConstants(String description,String editable) {
		this.description = description;
		this.isEditable = editable;
	}
	
	
	public String getDescription() {
		return this.description;
	}
	
	public String getIsEditable() {
		return this.isEditable;
	}
	

}
